# Generated by Django 5.2.8 on 2025-11-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
